### ISSUE TITLE
时区为空导致panic

### ISSUE THREAD

**Issue by WQT233** [aliyun/aliyun-odps-go-sdk#22]
odps.common.http_const第36行代码 var GMT, _ = time.LoadLocation("GMT")
需要内置GMT时区，然后由于MaxCompute服务器连接需要验证时区还不能有偏移量

**Comment by f0cii** [comment]
可以替换成：
var GMT = time.FixedZone("GMT", 0)
即可解决

**Comment by Albelt** [comment]
开发环境是Ubuntu没报这个错，但是容器像alpine这种，没带时区文件，所以要单独安装这个包，我是这么解决的：

```
FROM xxx/alpine:3.10

RUN apk update && apk add tzdata \
...
```
