### ISSUE TITLE
 go mod tidy 报错了

### ISSUE THREAD

**Issue by lianganyi** [aliyun/aliyun-odps-go-sdk#3]
尝试执行 examples 里的示例 , go mod tidy 报错了

PS D:\Codes\go\src\odps> go mod tidy
go: downloading github.com/aliyun/aliyun-odps-go-sdk/arrow v0.0.0-00010101000000-000000000000
go: finding module for package github.com/stretchr/testify/require
go: finding module for package github.com/stretchr/testify/assert
go: found github.com/stretchr/testify/assert in github.com/stretchr/testify v1.8.1
go: found github.com/stretchr/testify/require in github.com/stretchr/testify v1.8.1
odps imports
        github.com/aliyun/aliyun-odps-go-sdk/sqldriver imports
        github.com/aliyun/aliyun-odps-go-sdk/odps/tunnel imports
        github.com/aliyun/aliyun-odps-go-sdk/arrow: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: reading https://goproxy.cn/github.com/aliyun/aliyun-odps-go-sdk/arrow/@v/v0.0.0-00010101000000-000000000000.zip: 404 Not Found
        server response: not found: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
odps imports
        github.com/aliyun/aliyun-odps-go-sdk/sqldriver imports
        github.com/aliyun/aliyun-odps-go-sdk/odps/tunnel imports
        github.com/aliyun/aliyun-odps-go-sdk/arrow/array: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: reading https://goproxy.cn/github.com/aliyun/aliyun-odps-go-sdk/arrow/@v/v0.0.0-00010101000000-000000000000.zip: 404 Not Found
        server response: not found: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
odps imports
        github.com/aliyun/aliyun-odps-go-sdk/sqldriver imports
        github.com/aliyun/aliyun-odps-go-sdk/odps/tunnel imports
        github.com/aliyun/aliyun-odps-go-sdk/arrow/ipc: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: reading https://goproxy.cn/github.com/aliyun/aliyun-odps-go-sdk/arrow/@v/v0.0.0-00010101000000-000000000000.zip: 404 Not Found
        server response: not found: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
odps imports
        github.com/aliyun/aliyun-odps-go-sdk/sqldriver imports
        github.com/aliyun/aliyun-odps-go-sdk/odps/tunnel tested by
        github.com/aliyun/aliyun-odps-go-sdk/odps/tunnel.test imports
        github.com/aliyun/aliyun-odps-go-sdk/arrow/memory: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: reading https://goproxy.cn/github.com/aliyun/aliyun-odps-go-sdk/arrow/@v/v0.0.0-00010101000000-000000000000.zip: 404 Not Found
        server response: not found: github.com/aliyun/aliyun-odps-go-sdk/arrow@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
PS D:\Codes\go\src\odps>

**Comment by fetchadd** [comment]
问题已修复
